language: python
python:
  - "3.6"
branches:
  only:
  - master
  - develop
services:
  - rabbitmq
install:
  - pip install pipenv --upgrade
  - pipenv install --dev
script:
  - pipenv run py.test tests --verbose --cov --cov-report term-missing --flake8 application
after_success:
  - coveralls
notifications:
    slack: pycolorado:S9WVa6L6dH9d0HPNU9bUUMof
