language: python
# Cache our Gcloud SDK and pip-installed libraries between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "$HOME/lib"
env:
  # Set the App engine install location and add the SDK to our Python path
  - GOOGLE_APP_ENGINE_SDK=${HOME}/google-cloud-sdk PYTHONPATH=${PYTHONPATH}:${GOOGLE_APP_ENGINE_SDK} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # If the SDK is not present, download it.  When it's available, pull it into our path.
  - if [ ! -f ${GOOGLE_APP_ENGINE_SDK}/path.bash.inc ]; then rm -rf ${GOOGLE_APP_ENGINE_SDK} && curl https://sdk.cloud.google.com | bash; fi
  - source ${GOOGLE_APP_ENGINE_SDK}/path.bash.inc
client-secret:
  json:
    secure: EMBfrZWQ2+UpVvL3c2GNXn+aAjIJg3C8dkCXUbBQ6CKuceEy/UwtCW2SX1xyrf8xH+NBAKpRAVkvdRJP9SOWgxxnit+bNM0JCM8i/WP8+m0hHF3NfBbvdfXTxIOGUFTGttdnABcN3HAFDjdoezKuBEcYpt7tE5bQVfTBac6CypXsfUunpaGh0CYXleQZ0ZhsHEv280e50C6fOhMhzEpHlupfUn4Ka3uLpxqez0M0a4IkkuBCzS5ij+fAPK0Kc95UghRLwFuXV3eSLDKVu/xsw9YOtyIj6LYar3u3vjM5kMvPy2SXFMM10SGjvdIfgf1y1lVdTAAcTC9ErY4brG9eFP6zOuTTWeqKWxdPQD5SiTijnlnInUvKz+KbNfPtJGJm7QGktPc4mgTSEhNXrVR1y91Pjj64UzG7heignPJDcNvb0QG95ibgQbAMSIu3citglHe3+2dp2ElRb1GswtMJfPQU3k3Qnceo9nutnA4v7ruxYJMBwkKptoHBDO2euLp4ISh046kJLvjk6jR8sMPVXD0k18zskDs61VNMHmXdJuG4894ecl0aoi5lfA8g9j/gamBWdlcwrM+qUvTVAp4I4iYSfjdnyPcVHyl3aVvxXc+mkz0NhZaneDy79zF+q2E4NprF5fxeRqvu77x1dbgCtNGFjrny967sbTfIFE0GC/k=
install:
  # Install the Python dependencies
  - pip install -r requirements.txt
  # Install and update additional GAE components
  - gcloud config set project boulder-python
  - gcloud -q components install app-engine-python
  - gcloud -q components update
script:
  # Run the unit tests
  - py.test
deploy:
  # Deploy the app
  skip_cleanup: true
  provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master
