application: unique-name
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: application/static/css
- url: /js
  static_dir: application/static/js
- url: /img
  static_dir: application/static/img
- url: .*  # This regex directs all routes to main.app
  script: run.app

skip_files:
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.haml
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.less
- ^/docs*

libraries:
- name: jinja2
  version: latest
