"""empty message

Revision ID: c1fc3b901ee0
Revises: 0339ecb01100
Create Date: 2018-11-21 16:52:09.352101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fc3b901ee0'
down_revision = '0339ecb01100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trellolist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('list_symbolic_name', sa.String(length=255), nullable=False),
    sa.Column('list_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id'),
    sa.UniqueConstraint('list_symbolic_name')
    )
    op.add_column('submission', sa.Column('card_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'card_email')
    op.drop_table('trellolist')
    # ### end Alembic commands ###
